include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - apps/**/*.config.dart
    - apps/**/*.g.dart
    - packages/**/*.config.dart
    - packages/**/*.g.dart
    - templates/**/__brick__/**

linter:
  rules:
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - always_put_required_named_parameters_first
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_relative_imports
