name: monorepo_mason
publish_to: none

environment:
  sdk: ^3.12.0

dev_dependencies:
  melos: ^7.8.0
  flutter_lints: ^6.0.0

workspace:
  - apps/**
  - packages/**
  - templates/**/hooks/

melos:
  ide:
    intellij:
      enabled: false
  command:
    bootstrap:
      environment:
        sdk: ^3.12.0
        flutter: ">=1.17.0"
      dependencies:
        get_it: ^9.2.1
        injectable: ^3.0.0
        bloc: ^9.2.1
        flutter_bloc: ^9.1.1
        go_router: ^17.2.3
        equatable: ^2.0.8
        meta: ^1.18.2
        collection: ^1.19.1
        flutter_smart_dialog: ^5.1.0
        mason: ^0.1.0
      dev_dependencies:
        flutter_lints: ^6.0.0
        melos: ^7.8.0
        build_runner: ^2.15.0
        injectable_generator: ^3.0.2
    clean:
      hooks:
        post: |
          melos di:clean
          find . -name 'pubspec.lock' -delete
          find . -name '*.config.dart' -delete
          find . -name 'Podfile.lock' -delete

  scripts:
    workspace:list:
      description: List all packages included in the workspace.
      run: dart pub workspace list

    di:generate:
      description: Generate files for dependency injection
      run: melos exec -c 1 --fail-fast -- "dart run build_runner build -d"

    di:clean:
      description: Clean generated files of dependency injection
      run: melos exec -c 1 --fail-fast -- "dart run build_runner clean"

    mason:clean:
      description: Clears the local Mason cache.
      run: mason cache clear

    mason:get:
      description: Downloads and installs all Mason brick dependencies.
      run: mason get

    build:workspace:
      steps:
        - melos clean && melos bs
        - melos di:generate

