name: monorepo_mason
publish_to: none

environment:
  sdk: ^3.12.0

dev_dependencies:
  melos: ^7.8.0
  flutter_lints: ^6.0.0

workspace:
  - templates/**/hooks
  - packages/**

melos:
  ide:
    intellij:
      enabled: false
  command:
    bootstrap:
      environment:
        sdk: ^3.12.0
        flutter: ">=1.17.0"
      dependencies:
        mason: ^0.1.0
      dev_dependencies:
        flutter_lints: ^6.0.0
        melos: ^7.8.0
      hooks:
        post: |
          mason get
    clean:
      hooks:
        post: |
          mason cache clear

  scripts:
    workspace:list:
      description: List all packages included in the workspace.
      run: dart pub workspace list

